Repository SE701-T5/Backend, pull requests merged in 2022-03, with the labels that each got.

#5 Add Node.js Continuous Integration Workflow
  .github/workflows/node.js.yml
  .gitignore
  package-lock.json
  package.json
  test/empty.test.js
Labels: enhancement

#12 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#9 Add pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#7 Add CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#3 Add CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#26 Setup Backend Server
  config/db.server.config.js
  config/express.server.config.js
  controllers/db.server.controller.js
  controllers/forum.server.controller.js
  controllers/user.server.controller.js
  models/db.server.model.js
  models/forum.server.model.js
  models/user.server.model.js
  package-lock.json
  package.json
  routes/db.server.routes.js
  routes/forum.server.routes.js
  routes/user.server.routes.js
  server.js
  test/db.test.js
  test/forum.test.js
  test/user.test.js
Labels: enhancement

#34 Add DB forum post schema.
  config/db_schemas/forum.schema.js
  package-lock.json
  package.json
  test/schemas.test.js
Labels: enhancement

#32 Add DB forum user schema
  config/db_schemas/user.schema.js
  test/schemas.test.js
Labels: enhancement

#36 Implement database connection
  .github/workflows/node.js.yml
  config/db.server.config.js
  package-lock.json
  package.json
  server.js
  test/db.connection.test.js
  test/db.test.js
  test/forum.test.js
  test/user.test.js
Labels: bug, enhancement

#43 Fix Pull Request CI Workflow
  .github/workflows/node.js.yml
Labels: bug

#44 Fix Pull Request CI Workflow
  .github/workflows/node.js.yml
Labels: bug

#41 Implement insert new forum post to database
  config/db.server.config.js
  config/db_schemas/forum.schema.js
  config/db_schemas/user.schema.js
  controllers/forum.server.controller.js
  models/forum.server.model.js
  server.js
  test/db.connection.test.js
  test/forum.test.js
  test/schemas.test.js
Labels: bug, enhancement

#48 add feature for Forum post search
  controllers/forum.server.controller.js
  models/forum.server.model.js
  test/forum.test.js
Labels: enhancement

#37 HTTP POST request for user creation
  config/db_schemas/user.schema.js
  controllers/user.server.controller.js
  models/user.server.model.js
  test/schemas.test.js
  test/user.test.js
Labels: enhancement

#49 Removal of forum post from DB by HTTP request
  controllers/forum.server.controller.js
  lib/validate.lib.js
  models/forum.server.model.js
  routes/forum.server.routes.js
  test/forum.test.js
  test/validate.test.js
Labels: bug, enhancement

#47 Implement request for database reset
  .github/workflows/node.js.yml
  controllers/db.server.controller.js
  models/db.server.model.js
  models/forum.server.model.js
  test/db.test.js
  test/forum.test.js
Labels: bug, enhancement

#35 adding feature of user search
  controllers/user.server.controller.js
  models/user.server.model.js
  test/user.test.js
Labels: enhancement

#54 Fix pull_request_template.md Broken Link
  .github/pull_request_template.md
Labels: bug, documentation

#53 Implement Forum Post Update Feature using HTTP PATCH
  controllers/forum.server.controller.js
  controllers/user.server.controller.js
  lib/validate.lib.js
  models/forum.server.model.js
  models/user.server.model.js
  test/forum.test.js
Labels: enhancement

#58 Add Heroku Continuous Deployment to Action Workflow
  .github/workflows/node.js.yml
Labels: enhancement

#57 Implement Forum User Update Feature using HTTP PATCH
  controllers/forum.server.controller.js
  controllers/user.server.controller.js
  models/forum.server.model.js
  models/user.server.model.js
  package-lock.json
  package.json
  test/user.test.js
Labels: enhancement

#59 Implement forum user deletion.
  controllers/user.server.controller.js
  models/user.server.model.js
  routes/user.server.routes.js
  test/user.test.js
Labels: enhancement

#56 Implement random name generation for forum user.
  controllers/user.server.controller.js
  test/user.test.js
Labels: enhancement

#62 Fix CI/CD Workflow for Main Repository
  .github/workflows/node.js.yml
Labels: bug

#64 Fix CI/CD sequential testing
  .github/workflows/node.js.yml
Labels: bug

#66 Fixed bug with heroku deployment.
  package.json
Labels: bug

#67 Fix package.json for Heroku Deployment
  package.json
Labels: bug

#68 Implement user authentication
  config/config.server.config.js
  config/db_schemas/user.schema.js
  config/express.server.config.js
  controllers/forum.server.controller.js
  controllers/user.server.controller.js
  lib/middleware.lib.js
  models/user.server.model.js
  package-lock.json
  package.json
  routes/forum.server.routes.js
  routes/user.server.routes.js
  test/authenticate.user.test.js
  test/db.test.js
  test/forum.test.js
  test/schemas.test.js
  test/user.test.js
Labels: enhancement

#73 Refactor test suite setup and teardown
  test/authenticate.user.test.js
  test/db.test.js
  test/forum.test.js
  test/user.test.js
Labels: enhancement

#71 Implement logout user funtionality
  controllers/user.server.controller.js
  models/user.server.model.js
  test/user.test.js
Labels: enhancement

#74 Update README.md
  README.md
Labels: documentation

#69 Implementing password hashing
  controllers/user.server.controller.js
  models/user.server.model.js
  package-lock.json
  package.json
  test/authenticate.user.test.js
  test/forum.test.js
  test/user.test.js
Labels: enhancement

#76 Fix main repo for demonstration
  .github/workflows/node.js.yml
  config/express.server.config.js
  controllers/user.server.controller.js
  test/user.test.js
Labels: bug

#60 Implement post request for comment creation
  .github/workflows/node.js.yml
  config/db_schemas/comment.schema.js
  config/db_schemas/forum.schema.js
  controllers/forum.server.controller.js
  controllers/user.server.controller.js
  models/db.server.model.js
  models/forum.server.model.js
  models/user.server.model.js
  test/comment.test.js
  test/forum.test.js
  test/schemas.test.js
  test/user.test.js
Labels: enhancement

#79 Implement search request for forum post comment
  controllers/forum.server.controller.js
  test/comment.test.js
Labels: enhancement

#88 Update README.md
  README.md
Labels: documentation

#94 update project files
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#95 convert to typescript
  .github/pull_request_template.md
  config/config.server.config.js
  config/config.server.config.ts
  config/db.server.config.js
  config/db.server.config.ts
  config/db_schemas/comment.schema.ts
  config/db_schemas/forum.schema.ts
  config/db_schemas/user.schema.ts
  config/express.server.config.ts
  controllers/db.server.controller.ts
  controllers/forum.server.controller.ts
  controllers/user.server.controller.ts
  lib/middleware.lib.ts
  lib/validate.lib.ts
  models/db.server.model.ts
  models/forum.server.model.js
  models/forum.server.model.ts
  models/user.server.model.ts
  package-lock.json
  package.json
  routes/db.server.routes.ts
  routes/forum.server.routes.ts
  routes/user.server.routes.ts
  server.ts
  test/authenticate.user.test.js
  test/authenticate.user.test.ts
  test/comment.test.ts
  test/db.connection.test.js
  test/db.connection.test.ts
  test/db.test.ts
  test/forum.test.ts
  test/global-fixtures.ts
  test/schemas.test.ts
  test/user.test.ts
  test/validate.test.ts
  tsconfig.json
Labels: enhancement

#99 setup code formatting tools
  .eslintrc.js
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/node.js.yml
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  README.md
  config/config.server.config.ts
  config/db.server.config.ts
  config/db_schemas/comment.schema.ts
  config/db_schemas/forum.schema.ts
  config/db_schemas/user.schema.ts
  config/express.server.config.ts
  controllers/db.server.controller.ts
  controllers/forum.server.controller.ts
  controllers/user.server.controller.ts
  lib/middleware.lib.ts
  lib/validate.lib.ts
  models/db.server.model.ts
  models/forum.server.model.ts
  models/user.server.model.ts
  package-lock.json
  package.json
  routes/db.server.routes.ts
  routes/forum.server.routes.ts
  routes/user.server.routes.ts
  server.ts
  test/authenticate.user.test.ts
  test/comment.test.ts
  test/db.connection.test.ts
  test/db.test.ts
  test/forum.test.ts
  test/global-fixtures.ts
  test/schemas.test.ts
  test/user.test.ts
  test/validate.test.ts
Labels: enhancement
